apiVersion: v1
kind: PersistentVolume
metadata:
  name: 3scale-system-redis-volume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  nfs:
    path: /exports/3scale/system-redis
    server: 1.2.3.4
  persistentVolumeReclaimPolicy: Retain
